"""Central limits for first-party MCP tools."""

from __future__ import annotations

QUERY_MIN_LENGTH = 1
QUERY_MAX_LENGTH = 500

SEARCH_DEFAULT_LIMIT = 5
SEARCH_MAX_LIMIT = 8

SCORE_THRESHOLD_MIN = 0.0
SCORE_THRESHOLD_MAX = 1.0

MAX_TAG_LENGTH = 100
MAX_PATH_LENGTH = 1_024

MAX_CHUNK_TEXT_LENGTH = 4_000
MAX_TOTAL_RESULT_TEXT_LENGTH = 30_000

DEFAULT_TOOL_TIMEOUT_SECONDS = 15.0